name: Quality assessment
 
on:
  push:
    #branches: [ master ]
    paths: [ 'src/**' ]
  workflow_dispatch:

env:
  NET_VERSION: '6.x'
  PROJECT_NAME: src/MB.Extensions 
  PROJECT_FILE: MB.Extensions.csproj  
  
jobs:
  build:
    name: Quality assessment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        
    - name: Setup .NET Core SDK ${{ env.NET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NET_VERSION }}
        
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test --configuration Release --no-build        
      
